<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NODE1099" ignored="0" name="midtrans tests" tests="4" failures="1" timestamp="21 Jul 2019 16:06:14 GMT" time="128.805" errors="0">
  <testcase name="testUserAbleToBuyPillowSuccessfully_TC01" time="20.358" classname="com.firstTestNG.tests.HomePageTest"/>
  <testcase name="testUserUnAbleToBuyPillow_TC02" time="20.527" classname="com.firstTestNG.tests.HomePageTest">
    <skipped/>
  </testcase> <!-- testUserUnAbleToBuyPillow_TC02 -->
  <testcase name="testUserUnAbleToBuyPillow_TC02" time="20.033" classname="com.firstTestNG.tests.HomePageTest">
    <skipped/>
  </testcase> <!-- testUserUnAbleToBuyPillow_TC02 -->
  <testcase name="testUserUnAbleToBuyPillow_TC02" time="21.93" classname="com.firstTestNG.tests.HomePageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Retry link is not getting displayed expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Retry link is not getting displayed expected [false] but found [true]
at com.firstTestNG.tests.HomePageTest.testUserUnAbleToBuyPillow_TC02(HomePageTest.java:59)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testUserUnAbleToBuyPillow_TC02 -->
</testsuite> <!-- midtrans tests -->
